In [6]:
import pandas as pd
from pandasql import sqldf

In [8]:
# Goal: Append quarterly financials (compustat) to monthly data (crsp) 
crsp = pd.read_sas("crsp_nasdaq100.sas7bdat", encoding= "ISO-8859-1 ") # monthly, starts 2020
compustat = pd.read_sas("compustat_nasdaq100.sas7bdat", encoding= "ISO-8859-1") #quarterly, starts 2019

In [15]:
sqldf("SELECT * FROM crsp LIMIT 5")

,PERMNO,DATE,CUSIP,COMNAM,TICKER,PRC,RET,SHROUT,VWRETD,SPRTRN,YEAR,MONTH,monthid
0,10107.0,2020-01-31 00:00:00.000000,59491810,MICROSOFT CORP,MSFT,170.229996,0.079455,7606047.0,-0.001728,-0.001628,2020,1,241
1,10107.0,2020-02-28 00:00:00.000000,59491810,MICROSOFT CORP,MSFT,162.009995,-0.045292,7606047.0,-0.077918,-0.084110,2020,2,242
2,10107.0,2020-03-31 00:00:00.000000,59491810,MICROSOFT CORP,MSFT,157.710007,-0.026541,7590000.0,-0.141733,-0.125119,2020,3,243
3,10107.0,2020-04-30 00:00:00.000000,59491810,MICROSOFT CORP,MSFT,179.210007,0.136326,7583440.0,0.129677,0.126844,2020,4,244
4,10107.0,2020-05-29 00:00:00.000000,59491810,MICROSOFT CORP,MSFT,183.250000,0.025389,7583440.0,0.053739,0.045282,2020,5,245

In [16]:
sqldf("SELECT * FROM compustat LIMIT 5")

,GVKEY,DATADATE,FYEARQ,FQTR,TIC,CONM,ATQ,CEQQ,EPSPXQ,IBQ,...,INDFMT,DATAFMT,POPSRC,DATAFQTR,DATACQTR,CURCDQ,COSTAT,YEAR,MONTH,monthid
0,001161,2019-03-31 00:00:00.000000,2019.0,1.0,AMD,ADVANCED MICRO DEVICES,4931.0,1788.0,0.01,16.0,...,INDL,STD,D,2019Q1,2019Q1,USD,A,2019,3,231
1,001161,2019-06-30 00:00:00.000000,2019.0,2.0,AMD,ADVANCED MICRO DEVICES,5102.0,1901.0,0.03,35.0,...,INDL,STD,D,2019Q2,2019Q2,USD,A,2019,6,234
2,001161,2019-09-30 00:00:00.000000,2019.0,3.0,AMD,ADVANCED MICRO DEVICES,5253.0,2176.0,0.11,120.0,...,INDL,STD,D,2019Q3,2019Q3,USD,A,2019,9,237
3,001161,2019-12-31 00:00:00.000000,2019.0,4.0,AMD,ADVANCED MICRO DEVICES,6028.0,2827.0,0.15,170.0,...,INDL,STD,D,2019Q4,2019Q4,USD,A,2019,12,240
4,001161,2020-03-31 00:00:00.000000,2020.0,1.0,AMD,ADVANCED MICRO DEVICES,5864.0,3037.0,0.14,162.0,...,INDL,STD,D,2020Q1,2020Q1,USD,A,2020,3,243

In [11]:
crsp['YEAR'] = pd.DatetimeIndex(crsp['DATE']).year
crsp['MONTH'] = pd.DatetimeIndex(crsp['DATE']).month
crsp['monthid'] = ((crsp['YEAR']) - 2000) * 12 + crsp['MONTH']
sqldf("SELECT * FROM crsp LIMIT 5")

,PERMNO,DATE,CUSIP,COMNAM,TICKER,PRC,RET,SHROUT,VWRETD,SPRTRN,YEAR,MONTH,monthid
0,10107.0,2020-01-31 00:00:00.000000,59491810,MICROSOFT CORP,MSFT,170.229996,0.079455,7606047.0,-0.001728,-0.001628,2020,1,241
1,10107.0,2020-02-28 00:00:00.000000,59491810,MICROSOFT CORP,MSFT,162.009995,-0.045292,7606047.0,-0.077918,-0.084110,2020,2,242
2,10107.0,2020-03-31 00:00:00.000000,59491810,MICROSOFT CORP,MSFT,157.710007,-0.026541,7590000.0,-0.141733,-0.125119,2020,3,243
3,10107.0,2020-04-30 00:00:00.000000,59491810,MICROSOFT CORP,MSFT,179.210007,0.136326,7583440.0,0.129677,0.126844,2020,4,244
4,10107.0,2020-05-29 00:00:00.000000,59491810,MICROSOFT CORP,MSFT,183.250000,0.025389,7583440.0,0.053739,0.045282,2020,5,245

In [12]:
compustat['YEAR'] = pd.DatetimeIndex(compustat['DATADATE']).year
compustat['MONTH'] = pd.DatetimeIndex(compustat['DATADATE']).month
compustat['monthid'] = ((compustat['YEAR']) - 2000) * 12 + compustat['MONTH']
sqldf("SELECT * FROM compustat LIMIT 5")

,GVKEY,DATADATE,FYEARQ,FQTR,TIC,CONM,ATQ,CEQQ,EPSPXQ,IBQ,...,INDFMT,DATAFMT,POPSRC,DATAFQTR,DATACQTR,CURCDQ,COSTAT,YEAR,MONTH,monthid
0,001161,2019-03-31 00:00:00.000000,2019.0,1.0,AMD,ADVANCED MICRO DEVICES,4931.0,1788.0,0.01,16.0,...,INDL,STD,D,2019Q1,2019Q1,USD,A,2019,3,231
1,001161,2019-06-30 00:00:00.000000,2019.0,2.0,AMD,ADVANCED MICRO DEVICES,5102.0,1901.0,0.03,35.0,...,INDL,STD,D,2019Q2,2019Q2,USD,A,2019,6,234
2,001161,2019-09-30 00:00:00.000000,2019.0,3.0,AMD,ADVANCED MICRO DEVICES,5253.0,2176.0,0.11,120.0,...,INDL,STD,D,2019Q3,2019Q3,USD,A,2019,9,237
3,001161,2019-12-31 00:00:00.000000,2019.0,4.0,AMD,ADVANCED MICRO DEVICES,6028.0,2827.0,0.15,170.0,...,INDL,STD,D,2019Q4,2019Q4,USD,A,2019,12,240
4,001161,2020-03-31 00:00:00.000000,2020.0,1.0,AMD,ADVANCED MICRO DEVICES,5864.0,3037.0,0.14,162.0,...,INDL,STD,D,2020Q1,2020Q1,USD,A,2020,3,243

In [20]:
df_compustat_crsp = sqldf("SELECT a.*, b.* \
                           FROM crsp as a \
                           LEFT JOIN compustat as b \
                           ON a.TICKER = b.TIC and a.monthid >= b.monthid + 4 and a.monthid <= b.monthid + 6")